name: Docker Image CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Debug
      run: |
        pwd
        ls -la
      working-directory: dummycloud

    - name: Set working directory
      run: cd deye-microinverter-cloud-free/deye-microinverter-cloud-free/dummycloud
      working-directory: dummycloud
    
    - name: Build the Docker image
      run: docker build . -t deye-dummycloud:latest
